default_install_hook_types: [pre-commit, post-checkout, pre-push]

repos:
-   repo: local
    hooks:

    -   id: autoflake
        name: autoflake
        description: remove unuser imports
        entry: autoflake
        language: python
        types: [python]
        stages: [pre-commit]
        args: ["--remove-all-unused-imports", "--remove-unused-variables"]

    -   id: autopep8
        name: autopep8
        description: autopep8
        entry: autopep8
        language: python
        types: [python]
        args: ["--in-place"]
        stages: [pre-commit]

    -   id: isort
        name: isort
        description: isort
        entry: isort
        language: python
        types: [python]
        stages: [pre-commit]

    -   id: flake8
        name: flake8
        description: flake8
        entry: flake8
        language: python
        types: [python]
        stages: [pre-commit]

    -   id: mypy
        name: mypy
        description: mypy
        entry: mypy
        language: python
        types: [python]
        stages: [pre-commit]

    -   id: bandit
        name: bandit
        description: bandit
        entry: bandit
        language: python
        types: [python]
        args: ["-c", "bandit.yaml", "-r", "."]
        stages: [pre-commit]

    -   id: pytest
        name: running tests
        description: pytest testing
        entry: poetry run pytest
        language: system
        types: [python]
        args: ["-v", "--disable-warnings"]
        always_run: true
        stages: [pre-push]

-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.1'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-install
        stages: [post-checkout]
