repos:
-   repo: local
    hooks:

    -   id: autopep8
        name: autopep8
        description: autopep8
        entry: autopep8
        language: python
        types: [python]
        args: ["--in-place"]

    -   id: isort
        name: isort
        description: isort
        entry: isort
        language: python
        types: [python]

    -   id: flake8
        name: flake8
        description: flake8
        entry: flake8
        language: python
        types: [python]

    -   id: mypy
        name: mypy
        description: mypy
        entry: mypy
        language: python
        types: [python]

    -   id: bandit
        name: bandit
        description: bandit
        entry: bandit
        language: python
        types: [python]
