"""create tables

Revision ID: 0a13c54fb70f
Revises: 
Create Date: 2024-02-26 22:22:37.690396

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0a13c54fb70f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('user_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('auth_user_id'),
    sa.UniqueConstraint('auth_user_id'),
    sa.UniqueConstraint('email'),
    schema='auth_service'
    )
    op.create_table('user_session',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_service.auth_user.auth_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('session_id'),
    schema='auth_service'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_session', schema='auth_service')
    op.drop_table('auth_user', schema='auth_service')
    # ### end Alembic commands ###
