"""create user table

Revision ID: 5ce3150a5d14
Revises: 
Create Date: 2024-01-28 22:13:10.924421

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5ce3150a5d14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
                    sa.Column('auth_user_id', sa.UUID(), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('password', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('auth_user_id'),
                    sa.UniqueConstraint('auth_user_id'),
                    sa.UniqueConstraint('email'),
                    schema='auth_service'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_user', schema='auth_service')
    # ### end Alembic commands ###
