"""start_app

Revision ID: 64059d339fe9
Revises: 
Create Date: 2024-03-02 22:06:18.945673

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '64059d339fe9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('user_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('auth_user_id'),
    sa.UniqueConstraint('auth_user_id'),
    sa.UniqueConstraint('email'),
    schema='auth_service'
    )
    op.create_table('role',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_id'),
    sa.UniqueConstraint('role_name'),
    schema='auth_service'
    )
    op.create_table('role_auth_user_association',
    sa.Column('role_auth_user_association_id', sa.UUID(), nullable=False),
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_service.auth_user.auth_user_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth_service.role.role_id'], ),
    sa.PrimaryKeyConstraint('role_auth_user_association_id'),
    sa.UniqueConstraint('auth_user_id', 'role_id', name='idx_unique_auth_user_id_role_id'),
    sa.UniqueConstraint('role_auth_user_association_id'),
    schema='auth_service'
    )
    op.create_table('user_session',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_service.auth_user.auth_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('session_id'),
    schema='auth_service'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_session', schema='auth_service')
    op.drop_table('role_auth_user_association', schema='auth_service')
    op.drop_table('role', schema='auth_service')
    op.drop_table('auth_user', schema='auth_service')
    # ### end Alembic commands ###
