"""start_app

Revision ID: 88e720a13a21
Revises: 
Create Date: 2024-06-18 22:12:40.783461

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '88e720a13a21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('user_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('auth_user_id'),
    sa.UniqueConstraint('email'),
    schema='auth_service'
    )
    op.create_table('role',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name'),
    schema='auth_service'
    )
    op.create_table('claim',
    sa.Column('claim_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_name', sa.String(length=15), nullable=False),
    sa.Column('claim_value', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_service.auth_user.auth_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id'),
    sa.UniqueConstraint('claim_name', 'user_id', name='idx_unique_user_id_claim_name'),
    schema='auth_service'
    )
    op.create_table('role_auth_user_association',
    sa.Column('role_auth_user_association_id', sa.UUID(), nullable=False),
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_service.auth_user.auth_user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_service.role.role_id'], ),
    sa.PrimaryKeyConstraint('role_auth_user_association_id'),
    sa.UniqueConstraint('auth_user_id', 'role_id', name='idx_unique_auth_user_id_role_id'),
    schema='auth_service'
    )
    op.create_table('user_session',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('login_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_service.auth_user.auth_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    schema='auth_service'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_session', schema='auth_service')
    op.drop_table('role_auth_user_association', schema='auth_service')
    op.drop_table('claim', schema='auth_service')
    op.drop_table('role', schema='auth_service')
    op.drop_table('auth_user', schema='auth_service')
    # ### end Alembic commands ###
