version: '3'

services:

  auth-db:
    container_name: "auth-db"
    image: postgres:13
    restart: always
    ports:
      - "35432:5432"
    env_file:
      - .env.auth-db
    volumes:
      - ../../db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql

  auth-redis:
    container_name: "auth-redis"
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
